package cbindings.portaudio.blocking.functions

import cbindings.portaudio.aliases.{PaError, PaStream}
import scala.scalanative.unsafe.{blocking, extern, CUnsignedLongInt, Ptr}

// In these particular cases, we define our own external functions (rather than use those generated by the bindgen)
// This is so we can use the blocking annotation and notify the GC not to wait for this unmanaged code
// See https://scala-native.org/en/stable/user/lang.html#multithreading for more details

@blocking def Pa_ReadStream(
    stream: Ptr[PaStream],
    buffer: Ptr[Byte],
    frames: CUnsignedLongInt
): PaError = extern

@blocking def Pa_WriteStream(
    stream: Ptr[PaStream],
    buffer: Ptr[Byte],
    frames: CUnsignedLongInt
): PaError = extern
